version: '3'
services:
  auth-mongodb:
    build:
      context: authorization-service/mongo
    image: ${PROJECT_NAME}/auth-mongodb:${TAG}
    networks:
      - ${NETWORK_HOST}
    ports:
      - "${MONGO_PORT}:40000"
  auth-app:
    build:
      context: authorization-service/fast-api
    image: ${PROJECT_NAME}/auth-app:${TAG}
    environment:
      - PORT=${AUTH_API_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - ${NETWORK_HOST}
    ports:
      - "${AUTH_API_PORT}:${AUTH_API_PORT}"
networks:
  backend_local: