version: '3'
services:
  auth-mongodb:
    build:
      context: authorization-service/mongo
    image: ${PROJECT_NAME}/auth-mongodb:${TAG}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - backend
    ports:
      - "27017:27017"
networks:
  backend: