version: '3'
services:
  auth-mongodb:
    build:
      context: authorization-service/mongo
    image: ${PROJECT_NAME}/auth-mongodb:${TAG}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - backend
    ports:
      - "27017:40000"
  auth-app:
    build:
      context: authorization-service/fast-api
    image: ${PROJECT_NAME}/auth-app:${TAG}
    environment:
      - PORT=40001
    networks:
      - backend
    ports:
      - "40001:40001"
networks:
  backend: